# render.yaml — deploy Agent vs Mole Telegram bot as a worker on Render
services:
  - type: worker
    name: agent-mole-bot
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8408074707:AAEe7miladjgSS4RyoxDNHFTdtgqfIJ0Fvc"
